# Generated by Django 3.1.6 on 2021-02-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Invoices_OUT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=100)),
                ('series', models.IntegerField()),
                ('number', models.IntegerField()),
                ('emitter', models.CharField(max_length=100)),
                ('emitter_name', models.CharField(max_length=100)),
                ('aditional_info', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices_OUT_PROD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=100)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoices_out')),
            ],
        ),
    ]
