# Generated by Django 3.1.6 on 2021-02-17 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices_out',
            name='emission_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
