# Generated by Django 3.1.6 on 2021-02-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20210217_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices_out',
            name='aditional_info',
            field=models.CharField(max_length=1000),
        ),
    ]
